### ISSUE TITLE
Update to use build.os in readthedocs.yml

### ISSUE THREAD

**Issue by RCheesley** [mautic/developer-documentation-new#151]
According to the blog post here: https://blog.readthedocs.com/use-build-os-config/ and the docs here: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os we need to switch to using build.os.

Small change needed, see https://blog.readthedocs.com/use-build-os-config/ for the details.

**Comment by nick-vanpraet** [comment]
Seems to be already fixed?

https://github.com/mautic/developer-documentation-new/blob/5.x/.readthedocs.yaml#L10

Unless it's in another file that it has to be changed.

**Comment by RCheesley** [comment]
Yes, can be closed thanks!
