### ISSUE TITLE
Broken reference block

### ISSUE THREAD

**Issue by RCheesley** [mautic/developer-documentation-new#213]
Just noticed this as I was coming through the docs, looks like a broken reference doc at the bottom of the page:

https://devdocs.mautic.org/en/5.x/plugins/dependencies.html

**Comment by ifeoluwafavour** [comment]
Please may I be assigned this issue? @RCheesley

**Comment by RCheesley** [comment]
Absolutely @ifeoluwafavour - let us know if you need any help figuring it out. I expect it's just an incorrect syntax somewhere!

**Comment by ifeoluwafavour** [comment]
Okay. I will reach out if I need help with anything

**Comment by ifeoluwafavour** [comment]
hello @RCheesley I have created a pull request referencing this issue
