### ISSUE TITLE
Write documentation for Webhook events and payloads component

### ISSUE THREAD

**Issue by favour-chibueze** [mautic/developer-documentation-new#216]
We need to write documentation on the Webhook events and payloads component.

 https://devdocs.mautic.org/en/5.x/webhooks/events/index.html

**Comment by ifeoluwafavour** [comment]
Hello @favour-chibueze 
May I be assigned this issue?

**Comment by favour-chibueze** [comment]
Sure, I just assigned you the issue

**Comment by ifeoluwafavour** [comment]
Okay
Thank you!

**Comment by ifeoluwafavour** [comment]
Hello, @favour-chibueze @RCheesley 
I have created a PR that resolves this issue
