### ISSUE TITLE
Write documentation for Forms component

### ISSUE THREAD

**Issue by RCheesley** [mautic/developer-documentation-new#61]
We need to bring over, update and convert to RST the docs on the Form component.

https://developer.mautic.org/#forms

**Comment by dennisameling** [comment]
So there's two sections regarding forms:

https://developer.mautic.org/#extending-forms
https://developer.mautic.org/#forms

The first one is pretty much ready in https://github.com/mautic/developer-documentation-new/pull/28. I'll extract it into its own PR and will then add the other forms-related section as well.
