### ISSUE TITLE
Write documentation for Integrations

### ISSUE THREAD

**Issue by RCheesley** [mautic/developer-documentation-new#62]
We need to complete the documentation for the Integrations component:

https://mautic-developer.readthedocs.io/en/latest/components/integrations.html

See https://developer.mautic.org/#extending-integrations

**Comment by shinde-rahul** [comment]
@RCheesley @escopecz @fedys 
I was thinking of making this documentation as per the following structure,

- Getting started
- Directory Structure (Namespaces):
  - Asset
  - Command
  - Config
  - Controller
  - Entity
  - EventListner
  - Event
  - Form
  - Integration
  - Migrations
  - Model
  - Security
  - Segment
  - Sync
  - Tests
  - Translations
  - Views
- The metafile, Config/config.php
- Registering Integration (NameSpace: Integration)
- Different interfaces for configuration, like
  - Auth setting,
  - Features setting,
  - Field mapping,
  - Authorization,
  - Builders
- Creating Forms
- Adding schema and Updating schema
- Adding permissions
- Events and Event Subscribers
  - Lead
  - Campaign
  - Email
  - Token
  - Segment Filters
  - Points
- Command
- Installing, upgrading, and uninstalling

Please let me know If you have any other way to re-arrange this.

**Comment by RCheesley** [comment]
Sounds good to me! @dennisameling any thoughts?
