### ISSUE TITLE
Write documentation on the Points component

### ISSUE THREAD

**Issue by RCheesley** [mautic/developer-documentation-new#66]
We need to write the documentation for the Points component.

https://developer.mautic.org/#add-points

https://developer.mautic.org/#point-actions

https://developer.mautic.org/#point-triggers

https://mautic-developer.readthedocs.io/en/latest/components/points.html

**Comment by shinde-rahul** [comment]
@RCheesley, This https://developer.mautic.org/#add-points is a document for API. I don't see any directory in the repo catering to API docs. If yes, please help with pointers, or let me know how we should be moving ahead.
