### ISSUE TITLE
Port documentation on REST API

### ISSUE THREAD

**Issue by dennisameling** [mautic/developer-documentation-new#97]
TIP: use `m2r` to convert `.md` files from the old developer docs into `.rst`. When using this converter, most of these docs shouldn't take more than ~20 mins to migrate over.

Here's an example of ``m2r`` - this converter also converts tables into ``list-table`` directives properly.

```
pip install m2r
# This creates a new file with the .rst extension:
m2r my_markdown_file.md
```

- [x] Error handling https://github.com/mautic/developer-documentation-new/pull/145
- [x] Mautic version check https://github.com/mautic/developer-documentation-new/pull/145
- [x] Authorization https://github.com/mautic/developer-documentation-new/pull/145
- [x] API Rate Limiter https://github.com/mautic/developer-documentation-new/pull/145
- [x] Libraries https://github.com/mautic/developer-documentation-new/pull/145
- [x] Endpoints https://github.com/mautic/developer-documentation-new/pull/145
- [x] Assets https://github.com/mautic/developer-documentation-new/pull/100
- [x] Campaigns https://github.com/mautic/developer-documentation-new/pull/100
- [x] Categories https://github.com/mautic/developer-documentation-new/pull/100
- [x] Companies https://github.com/mautic/developer-documentation-new/pull/137
- [x] Contacts (by far the largest one) https://github.com/mautic/developer-documentation-new/pull/90
- [x] Data - Dashboard widget data https://github.com/mautic/developer-documentation-new/pull/144
- [x] Dynamic Content https://github.com/mautic/developer-documentation-new/pull/144
- [x] Emails https://github.com/mautic/developer-documentation-new/pull/139
- [x] Fields https://github.com/mautic/developer-documentation-new/pull/100
- [x] Files https://github.com/mautic/developer-documentation-new/pull/139
- [x] Forms https://github.com/mautic/developer-documentation-new/pull/136
- [x] Marketing Messages https://github.com/mautic/developer-documentation-new/pull/139
- [x] Notes https://github.com/mautic/developer-documentation-new/pull/139
- [x] Notifications https://github.com/mautic/developer-documentation-new/pull/132
- [x] Pages https://github.com/mautic/developer-documentation-new/pull/139
- [x] Point Actions https://github.com/mautic/developer-documentation-new/pull/144
- [x] Point Triggers https://github.com/mautic/developer-documentation-new/pull/144
- [x] Reports https://github.com/mautic/developer-documentation-new/pull/90
- [x] Roles https://github.com/mautic/developer-documentation-new/pull/139
- [x] Segments https://github.com/mautic/developer-documentation-new/pull/139
- [x] Text messages https://github.com/mautic/developer-documentation-new/pull/90
- [x] Stages https://github.com/mautic/developer-documentation-new/pull/143
- [x] Stats https://github.com/mautic/developer-documentation-new/pull/143
- [x] Tags https://github.com/mautic/developer-documentation-new/pull/143
- [x] Themes https://github.com/mautic/developer-documentation-new/pull/143
- [x] Tweets https://github.com/mautic/developer-documentation-new/pull/143
- [x] Users https://github.com/mautic/developer-documentation-new/pull/139
- [x] Webhooks https://github.com/mautic/developer-documentation-new/pull/144

**Comment by dennisameling** [comment]
@RCheesley we forgot to add a separate issue for the REST API, so I just added it. Luckily, most sections should be very quick to convert.

**Comment by RCheesley** [comment]
I _think_ that we might be done here, @dennisameling ? 🚀

**Comment by dennisameling** [comment]
Just the [one PR](https://github.com/mautic/developer-documentation-new/pull/145)! Just finished it so it's ready for review 😊

**Comment by dennisameling** [comment]
All API-related PRs have been merged, so this is now _finally_ complete! 🎉

**Comment by RCheesley** [comment]
Yasssss! Thank you so much for all your work on this @dennisameling 🚀
